
/* Item defines - [Item name] [single space] [Item ID of item] */


#define TYPES_TOTAL 18

/* TYPE ITEM */
#define ITEM_ID_CLEAR_SHARD 0xE4
#define ITEM_ID_SILK_SCARF 0xD9
#define ITEM_ID_FOCUSED_SWEAT 0xE5
#define ITEM_ID_BLACK_BELT 0xCF
#define ITEM_ID_LIGHT_FEATHER 0xE6
#define ITEM_ID_SHARP_BEAK 0xD2
#define ITEM_ID_POISON_DROP 0xE7
#define ITEM_ID_POISON_BARB 0xD3
#define ITEM_ID_GLEAMING_SAND 0xE8
#define ITEM_ID_SOFT_SAND 0xCB
#define ITEM_ID_JAGGED_SLIVER 0xE9
#define ITEM_ID_HARD_STONE 0xCC
#define ITEM_ID_POLLEN 0xEA
#define ITEM_ID_SILVER_POWDER 0xBC
#define ITEM_ID_SPIRIT_ORB 0xEB
#define ITEM_ID_SPELL_TAG 0xD5
#define ITEM_ID_METAL_SHAVING 0xEC
#define ITEM_ID_METAL_COAT 0xC7
#define ITEM_ID_LIVING_EMBER 0xED
#define ITEM_ID_CHARCOAL 0xD7
#define ITEM_ID_WATER_GLOBULE 0xEE
#define ITEM_ID_MYSTIC_WATER 0xD1
#define ITEM_ID_PLANT_FIBER 0xEF
#define ITEM_ID_MIRACLE_SEED 0xCD
#define ITEM_ID_POWER_CELL 0xF0
#define ITEM_ID_MAGNET 0xD0
#define ITEM_ID_BRAIN_CELL 0xF1
#define ITEM_ID_TWISTED_SPOON 0xD6
#define ITEM_ID_SNOWFLAKE 0xF2
#define ITEM_ID_NEVER_MELT_ICE 0xD4
#define ITEM_ID_SCALE_FRAG 0xF3
#define ITEM_ID_DRAGON_FANG 0xD8
#define ITEM_ID_HELD_ANGER 0xF4
#define ITEM_ID_BLACK_GLASSES 0xCE
#define ITEM_ID_FAIRY_DUST 0xF5
#define ITEM_ID_FAIRY_PLATE 0xF6


#define SHARED_TOTAL 41

/* SHARED ITEM */
#define ITEM_ID_STICK 0xE3
#define ITEM_ID_PEBBLE 0xE2
#define ITEM_ID_BLUE_SHARD 0x31
#define ITEM_ID_YELLOW_SHARD 0x32
#define ITEM_ID_RED_SHARD 0x30
#define ITEM_ID_GREEN_SHARD 0x33
#define ITEM_ID_BERRY_JUICE 0x2C
#define ITEM_ID_MOON_STONE 0x5E
#define ITEM_ID_SUN_STONE 0x5D
#define ITEM_ID_LEAF_STONE 0x62
#define ITEM_ID_FIRE_STONE 0x5F
#define ITEM_ID_THUNDER_STONE 0x60
#define ITEM_ID_WATER_STONE 0x61
#define ITEM_ID_ENERGY_POWDER 0x1E
#define ITEM_ID_HEAL_POWDER 0x20
#define ITEM_ID_BRIGHT_POWDER 0xB3
#define ITEM_ID_EVERSTONE 0xC3
#define ITEM_ID_QUICK_CLAW 0xB7
#define ITEM_ID_KINGS_ROCK 0xBB
#define ITEM_ID_DRAGON_SCALE 0xC9
#define ITEM_ID_LUCKY_EGG 0xC5
#define ITEM_ID_LEFTOVERS 0xC8
#define ITEM_ID_MENTAL_HERB 0xB9
#define ITEM_ID_WHITE_HERB 0xB4
#define ITEM_ID_ENERGY_ROOT 0x1F
#define ITEM_ID_LAVA_COOKIE 0x26
#define ITEM_ID_HEART_SCALE 0x5
#define ITEM_ID_TINY_MUSHROOM 0x67
#define ITEM_ID_PEARL 0x6A
#define ITEM_ID_BIG_MUSHROOM 0x68
#define ITEM_ID_BIG_PEARL 0x6B
#define ITEM_ID_STARDUST 0x6C
#define ITEM_ID_STAR_PIECE 0x6D
#define ITEM_ID_NUGGET 0x6E
#define ITEM_ID_HEART_SCALE 0x6F
#define ITEM_ID_REVIVAL_HERB 0x21
#define ITEM_ID_SACRED_ASH 0x2D
#define ITEM_ID_POKEBALL 0x4
#define ITEM_ID_ESCAPE_ROPE 0x55
#define ITEM_ID_POTION 0xD
#define ITEM_ID_HYPER_POTION 0x15


#define TM_TOTAL 50

/* TM ITEM */
#define ITEM_ID_TM01 0x121
#define ITEM_ID_TM02 0x122
#define ITEM_ID_TM03 0x123
#define ITEM_ID_TM04 0x124
#define ITEM_ID_TM05 0x125
#define ITEM_ID_TM06 0x126
#define ITEM_ID_TM07 0x127
#define ITEM_ID_TM08 0x128
#define ITEM_ID_TM09 0x129
#define ITEM_ID_TM10 0x12A
#define ITEM_ID_TM11 0x12B
#define ITEM_ID_TM12 0x12C
#define ITEM_ID_TM13 0x12D
#define ITEM_ID_TM14 0x12E
#define ITEM_ID_TM15 0x12F
#define ITEM_ID_TM16 0x130
#define ITEM_ID_TM17 0x131
#define ITEM_ID_TM18 0x132
#define ITEM_ID_TM19 0x133
#define ITEM_ID_TM20 0x134
#define ITEM_ID_TM21 0x135
#define ITEM_ID_TM22 0x136
#define ITEM_ID_TM23 0x137
#define ITEM_ID_TM24 0x138
#define ITEM_ID_TM25 0x139
#define ITEM_ID_TM26 0x130
#define ITEM_ID_TM27 0x13A
#define ITEM_ID_TM28 0x13B
#define ITEM_ID_TM29 0x13C
#define ITEM_ID_TM30 0x13D
#define ITEM_ID_TM31 0x13F
#define ITEM_ID_TM32 0x140
#define ITEM_ID_TM33 0x141
#define ITEM_ID_TM34 0x142
#define ITEM_ID_TM35 0x143
#define ITEM_ID_TM36 0x144
#define ITEM_ID_TM37 0x145
#define ITEM_ID_TM38 0x146
#define ITEM_ID_TM39 0x147
#define ITEM_ID_TM40 0x148
#define ITEM_ID_TM41 0x149
#define ITEM_ID_TM42 0x14A
#define ITEM_ID_TM43 0x14B
#define ITEM_ID_TM44 0x14C
#define ITEM_ID_TM45 0x14D
#define ITEM_ID_TM46 0x14E
#define ITEM_ID_TM47 0x14F
#define ITEM_ID_TM48 0x150
#define ITEM_ID_TM49 0x151
#define ITEM_ID_TM50 0x152


#define BERRY_TOTAL 43

/* BERRY ITEM */
#define ITEM_ID_CHERI 0x85
#define ITEM_ID_CHESTO 0x86
#define ITEM_ID_PECHA 0x87
#define ITEM_ID_RAWST 0x88
#define ITEM_ID_ASPEAR 0x89
#define ITEM_ID_LEPPA 0x8A
#define ITEM_ID_ORAN 0x8B
#define ITEM_ID_PERSIM 0x8C
#define ITEM_ID_LUM 0x8D
#define ITEM_ID_SITRUS 0x8E
#define ITEM_ID_FIGY 0x8F
#define ITEM_ID_WIKI 0x90
#define ITEM_ID_MAGO 0x91
#define ITEM_ID_AGUAV 0x92
#define ITEM_ID_IAPAPA 0x93
#define ITEM_ID_RAZZ 0x94
#define ITEM_ID_BLUK 0x95
#define ITEM_ID_NANAB 0x96
#define ITEM_ID_WEPEAR 0x97
#define ITEM_ID_PINAP 0x98
#define ITEM_ID_POMEG 0x99
#define ITEM_ID_KELPSY 0x9A
#define ITEM_ID_QUALOT 0x9B
#define ITEM_ID_HONDEW 0x9C
#define ITEM_ID_GREPA 0x9D
#define ITEM_ID_TOMATO 0x9E
#define ITEM_ID_CORNN 0x9F
#define ITEM_ID_MAGOST 0xA0
#define ITEM_ID_RABUTA 0xA1
#define ITEM_ID_NOMEL 0xA2
#define ITEM_ID_SPELON 0xA3
#define ITEM_ID_PAMTRE 0xA4
#define ITEM_ID_WATMEL 0xA5
#define ITEM_ID_DURIN 0xA6
#define ITEM_ID_BELUE 0xA7
#define ITEM_ID_LIECHI 0xA8
#define ITEM_ID_GANLON 0xA9
#define ITEM_ID_SALAC 0xAA
#define ITEM_ID_PETAYA 0xAB
#define ITEM_ID_APICOT 0xAC
#define ITEM_ID_LANSAT 0xAD
#define ITEM_ID_STARF 0xAE
#define ITEM_ID_ENIGMA 0xAF






u16 type_based_items[TYPES_TOTAL * 2] = {
    ITEM_ID_CLEAR_SHARD, ITEM_ID_SILK_SCARF,    // NORMAL
    ITEM_ID_FOCUSED_SWEAT, ITEM_ID_BLACK_BELT,    // FIGHTING
    ITEM_ID_LIGHT_FEATHER, ITEM_ID_SHARP_BEAK,    // FLYING
    ITEM_ID_POISON_DROP, ITEM_ID_POISON_BARB,    // POISON
    ITEM_ID_GLEAMING_SAND, ITEM_ID_SOFT_SAND,    // GROUND
    ITEM_ID_JAGGED_SLIVER, ITEM_ID_HARD_STONE,    // ROCK
    ITEM_ID_POLLEN, ITEM_ID_SILVER_POWDER    // BUG
    ITEM_ID_SPIRIT_ORB, ITEM_ID_SPELL_TAG,    // GHOST
    ITEM_ID_METAL_SHAVING, ITEM_ID_METAL_COAT,    // STEEL
    ITEM_ID_LIVING_EMBER, ITEM_ID_CHARCOAL,    // FIRE
    ITEM_ID_WATER_GLOBULE, ITEM_ID_MYSTIC_WATER,    // WATER
    ITEM_ID_PLANT_FIBER, ITEM_ID_MIRACLE_SEED,    // GRASS
    ITEM_ID_POWER_CELL, ITEM_ID_MAGNET,    // ELECTRIC
    ITEM_ID_BRAIN_CELL, ITEM_ID_TWISTED_SPOON,    // PSYCHIC
    ITEM_ID_SNOWFLAKE, ITEM_ID_NEVER_MELT_ICE,    // ICE
    ITEM_ID_SCALE_FRAG, ITEM_ID_DRAGON_FANG,    // DRAGON
    ITEM_ID_HELD_ANGER, ITEM_ID_BLACK_GLASSES,    // DARK
    ITEM_ID_FAIRY_DUST, ITEM_ID_FAIRY_PLATE,    // FAIRY
};

u16 shared_items[SHARED_TOTAL] = {
ITEM_ID_STICK,
ITEM_ID_PEBBLE,
ITEM_ID_BLUE_SHARD,
ITEM_ID_YELLOW_SHARD,
ITEM_ID_RED_SHARD,
ITEM_ID_GREEN_SHARD,
ITEM_ID_BERRY_JUICE,
ITEM_ID_MOON_STONE,
ITEM_ID_SUN_STONE,
ITEM_ID_LEAF_STONE,
ITEM_ID_FIRE_STONE,
ITEM_ID_THUNDER_STONE,
ITEM_ID_WATER_STONE,
ITEM_ID_ENERGY_POWDER,
ITEM_ID_HEAL_POWDER,
ITEM_ID_BRIGHT_POWDER,
ITEM_ID_EVERSTONE,
ITEM_ID_QUICK_CLAW,
ITEM_ID_KINGS_ROCK,
ITEM_ID_DRAGON_SCALE,
ITEM_ID_LUCKY_EGG,
ITEM_ID_LEFTOVERS,
ITEM_ID_MENTAL_HERB,
ITEM_ID_WHITE_HERB,
ITEM_ID_ENERGY_ROOT,
ITEM_ID_LAVA_COOKIE,
ITEM_ID_HEART_SCALE,
ITEM_ID_TINY_MUSHROOM,
ITEM_ID_PEARL,
ITEM_ID_BIG_MUSHROOM,
ITEM_ID_BIG_PEARL,
ITEM_ID_STARDUST,
ITEM_ID_STAR_PIECE,
ITEM_ID_NUGGET,
ITEM_ID_HEART_SCALE,
ITEM_ID_REVIVAL_HERB,
ITEM_ID_SACRED_ASH,
ITEM_ID_POKEBALL,
ITEM_ID_ESCAPE_ROPE,
ITEM_ID_POTION,
ITEM_ID_HYPER_POTION,
};

u16 tm_items[TM_TOTAL] = {
 ITEM_ID_TM09,
 ITEM_ID_TM46,
 ITEM_ID_TM49,
 ITEM_ID_TM48,
 ITEM_ID_TM45,
 ITEM_ID_TM41,
 ITEM_ID_TM37,
 ITEM_ID_TM33,
 ITEM_ID_TM32,
 ITEM_ID_TM18,
 ITEM_ID_TM17,
 ITEM_ID_TM10,
 ITEM_ID_TM21,
 ITEM_ID_TM27,
 ITEM_ID_TM16,
 ITEM_ID_TM12,
 ITEM_ID_TM11,
 ITEM_ID_TM07,
 ITEM_ID_TM06,
 ITEM_ID_TM05,
 ITEM_ID_TM04,
 ITEM_ID_TM03,
 ITEM_ID_TM19,
 ITEM_ID_TM28,
 ITEM_ID_TM34,
 ITEM_ID_TM39,
 ITEM_ID_TM47,
 ITEM_ID_TM43,
 ITEM_ID_TM42,
 ITEM_ID_TM31,
 ITEM_ID_TM02,
 ITEM_ID_TM30,
 ITEM_ID_TM36,
 ITEM_ID_TM35,
 ITEM_ID_TM29,
 ITEM_ID_TM24,
 ITEM_ID_TM13,
 ITEM_ID_TM23,
 ITEM_ID_TM26,
 ITEM_ID_TM14,
 ITEM_ID_TM22,
 ITEM_ID_TM25,
 ITEM_ID_TM38,
 ITEM_ID_TM50,
 ITEM_ID_TM01,
 ITEM_ID_TM15,
};

u16 berry_items[BERRY_TOTAL] = {
 ITEM_ID_CHERI,
 ITEM_ID_CHESTO,
 ITEM_ID_PECHA,
 ITEM_ID_RAWST,
 ITEM_ID_ASPEAR,
 ITEM_ID_LEPPA,
 ITEM_ID_ORAN,
 ITEM_ID_PERSIM,
 ITEM_ID_LUM,
 ITEM_ID_SITRUS,
 ITEM_ID_FIGY,
 ITEM_ID_WIKI,
 ITEM_ID_MAGO,
 ITEM_ID_AGUAV,
 ITEM_ID_IAPAPA,
 ITEM_ID_RAZZ,
 ITEM_ID_BLUK,
 ITEM_ID_NANAB,
 ITEM_ID_WEPEAR,
 ITEM_ID_PINAP,
 ITEM_ID_POMEG,
 ITEM_ID_KELPSY,
 ITEM_ID_QUALOT,
 ITEM_ID_HONDEW,
 ITEM_ID_GREPA,
 ITEM_ID_TOMATO,
 ITEM_ID_CORNN,
 ITEM_ID_MAGOST,
 ITEM_ID_RABUTA,
 ITEM_ID_NOMEL,
 ITEM_ID_SPELON,
 ITEM_ID_PAMTRE,
 ITEM_ID_WATMEL,
 ITEM_ID_DURIN,
 ITEM_ID_BELUE,
 ITEM_ID_LIECHI,
 ITEM_ID_GANLON,
 ITEM_ID_SALAC,
 ITEM_ID_PETAYA,
 ITEM_ID_APICOT,
 ITEM_ID_LANSAT,
 ITEM_ID_STARF,
 ITEM_ID_ENIGMA,
};